### ISSUE TITLE
Axe right button cannot interact

### ISSUE THREAD

**Issue by ghost** [blay09/ClientTweaks#62] opened 2023-01-06 12:20 UTC
### Minecraft Version

1.19 - 1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.3

### Mod Version

1.19-8.1.0

### Describe the Issue

Axe right button cannot interact

**Comment by BlayTheNinth** [comment] 2023-01-23 09:15
Duplicate of #52

**Closed as not planned by BlayTheNinth** 2023-01-23 09:15 UTC
Labels: Bug, Duplicate
