### ISSUE TITLE
'Disable Step Asssist' really disables step assist hard

### ISSUE THREAD

**Issue by ZeekDaGeek** [blay09/ClientTweaks#75] opened 2023-11-02 03:59 UTC
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### Mod Version

8.3.0

### Balm Version

4.6.0

### Describe the Issue

First I complain about step assist not working, now I complain that it does. There's no pleasing me.

Step assist now prevents you from walking up any height.

In this picture I'm trapped.
![image](https://github.com/TwelveIterationMods/ClientTweaks/assets/1709288/b7fc9c0c-f47a-4923-86d1-5752eee0d268)

**Comment by BlayTheNinth** [comment] 2023-12-07 21:31
Cannot reproduce and nothing that Client Tweaks is doing should be able to reduce vanilla's step height, as it only forces `maxUpStep` to Vanilla's `0.6` and multiplies Forge's `step_height_addition` by 0. Whatever mod is adding the step assist might be doing something weird.

**Comment by UnKZero** [comment] 2024-05-30 19:05
I had this same issue and was able to fix it by disabling a mod called apothic attributes.
May be unrelated to this case

**Comment by BlayTheNinth** [comment] 2024-06-11 10:23
Closing since 1.19 is no longer supported and this probably fixes itself in 1.21 where step height became a vanilla attribute.

**Closed as not planned by BlayTheNinth** 2024-06-11 10:23 UTC
Labels: Bug, Needs Repro, EOL, Forge
